version: "3.7"


services:
  db:
    image: postgres
    container_name: db_api_go
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=api_go
    volumes:
      - ./db:/data/